os:
  - linux

language: bash

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

before_script:
  - npm install --only=dev
  - chmod +x ./hack/make.sh

script:
  - ./hack/make.sh test --all

notifications:
  email:
    on_success: never
