stages:
  - test

jobs:
  include:
    - stage: test
      language: node_js
      os: linux
      node_js: 8
      before_install: if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi
      install: npm install --only=dev
      script: npm test

notifications:
  email:
    on_success: never
