os: linux
language: node_js
node_js: 8.9

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck
      - bats

before_script:
  - npm install --only=dev
  - chmod +x ./hack/make.sh

script:
  - ./hack/make.sh test --all

notifications:
  email:
    on_success: never
