os: linux
language: node_js
node_js: 8

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck
      - bats

before_install:
  - if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi

install:
  - npm install --only=dev

before_script:
  - chmod +x ./hack/make.sh

script:
  - ./hack/make.sh test --syntax --unit

notifications:
  email:
    on_success: never
