-- pdc
settings:
  verbose: false
  yaml:
    exclude:
      - pdcyml_plugin_execute
  file:
    log: install.log

executors:
  -
    command: shell
    function: pdcdef_executor_shell
  -
    command: sh
    function: pdcdef_executor_sh
  -
    command: bash
    function: pdcdef_executor_bash
  -
    command: plugin
    function: pdcdef_executor_plugin

path:
  root: ${PDCCONST_RUNNING_DIR}
  log: ${pdcyml_path_root}/log/
  tmp: ${pdcyml_path_root}/tmp/
  resources: ${pdcyml_path_root}/resources/
  scripts: ${pdcyml_path_root}/scripts/
  plugins: ${pdcyml_path_root}/plugins/

-- user
import:
  -

plugins:
  -

execute:
  -

-- plugin
plugin:
  setup:
    -
  execute:
    -
