settings:
  verbose: false
  path:
    install: ../
    log: ${pdcyml_settings_path_install}/log/
    tmp: ${pdcyml_settings_path_install}/tmp/
    resources: ${pdcyml_settings_path_install}/resources
    scripts: ${pdcyml_settings_path_install}/scripts
    plugins: ${pdcyml_settings_path_install}/plugins
  file:
    log: install.log

system:
  distro:
  version:
  arch:
  wm:

yaml_files:
  -

execute:
  -

plugins:
  get:
    -
  steps:
    import:
      -
    setup:
      -
    confirm:
      -
    execute:
      -
