settings:
  update_distro: true
  verbose: false
  system:
    distro: ""
    version: ""
    arch: ""
    wm: ""
  path:
    install: "../"
    log: "${settings_path_install}/log/"
    tmp: "${settings_path_install}/tmp/"
    resources: "${settings_path_install}/resources"
    scripts: "${settings_path_install}/scripts"
    plugins: "${settings_path_install}/plugins"
  file:
    log: "install.log"
  yaml_files:
    -
  dependencies:
    -
  pip:
    -
  gem:
    -
  npm:
    -
