settings:
  verbose: false
  yaml:
    exclude:
      - pdcyml_plugins_steps_execute
  path:
    install: ../
    log: ${pdcyml_settings_path_install}/log/
    tmp: ${pdcyml_settings_path_install}/tmp/
    resources: ${pdcyml_settings_path_install}/resources
    scripts: ${pdcyml_settings_path_install}/scripts
    plugins: ${pdcyml_settings_path_install}/plugins
  file:
    log: install.log

executors:
  -
    command: shell
    function: pdcdef_execute_shell
  -
    command: sh
    function: pdcdef_execute_sh
  -
    command: bash
    function: pdcdef_execute_bash
  -
    command: plugin
    function: pdcdef_execute_plugin

system:
  distro:
  version:
  arch:
  wm:

yaml_files:
  -

import:
  -

execute:
  -

plugins:
  get:
    -
  steps:
    import:
      -
    setup:
      -
    confirm:
      -
    execute:
      -
