settings:
  verbose: false
  yaml:
    exclude:
      - pdcyml_plugins_steps_execute
  file:
    log: install.log

executors:
  -
    command: shell
    function: pdcdef_execute_shell
  -
    command: sh
    function: pdcdef_execute_sh
  -
    command: bash
    function: pdcdef_execute_bash
  -
    command: plugin
    function: pdcdef_execute_plugin

path:
  root: ../
  log: ${pdcyml_path_root}/log/
  tmp: ${pdcyml_path_root}/tmp/
  resources: ${pdcyml_path_root}/resources/
  scripts: ${pdcyml_path_root}/scripts/
  plugins: ${pdcyml_path_root}/plugins/

yaml_files:
  -

import:
  -

execute:
  -

plugins:
  get:
    -
  steps:
    import:
      -
    setup:
      -
    confirm:
      -
    execute:
      -
